### PR TITLE
control: add ffmpeg

### PR DESCRIPTION
**Pull request by Ratatouilledummie**
ffmpeg provides necessary codecs implementations and is obrigatory for Epiphany. Epiphany Browser use ffmpeg for encoding/decoding video/music, without ffmpeg Epiphany can't play videos or musics from html/js players.

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]

**Comment by ghost** [comment]
This is great, was about to add it to my desktop today for LBRY desktop. How does one add it to their desktop from the base?

**Comment by kbdharun** [comment]
> This is great, was about to add it to my desktop today for LBRY desktop. How does one add it to their desktop from the base?

You will receive it in a future update. If you need it immediately, you can install it using ABRoot

**Comment by ghost** [comment]
> > This is great, was about to add it to my desktop today for LBRY desktop. How does one add it to their desktop from the base?
> 
> You will receive it in a future update. If you need it immediately, you can install it using ABRoot

I'll wait till it's received

**Comment by ghost** [comment]
> > This is great, was about to add it to my desktop today for LBRY desktop. How does one add it to their desktop from the base?
> 
> You will receive it in a future update. If you need it immediately, you can install it using ABRoot

what file path will it be located in?

**Comment by kbdharun** [comment]
> > > This is great, was about to add it to my desktop today for LBRY desktop. How does one add it to their desktop from the base?
> > 
> > 
> > You will receive it in a future update. If you need it immediately, you can install it using ABRoot
> 
> what file path will it be located in?

The package will be installed in root obviously.

**Pull request merged**
