### PR TITLE
2.0 Orchid Sid packages

### PR DESCRIPTION
**Pull request by matbme**
This PR replaces Ubuntu packages with debian equivalents and removes entirely some that are not needed.

List of changes:
- `gnome-control-center-faces`: Removed as there is no equivalent on Debian and I'm not sure what it does
- `fonts-khmeros-core`: Replaced with `fonts-khmeros`
- `fonts-ubuntu `: Deleted because we already ship Cantarell
- `ubuntu-gnome-wallpapers `: Deleted because we're no longer an Ubuntu distro
- `plymouth-theme-spinner`: Replaced with `plymouth-themes`

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]

**Comment by mirkobrombin** [comment]
Removing the Ubuntu font means that we must update the First setup and Installer to use Cantarell for the terminal view (I am not sure why we use Ubuntu there)

Is this ready for merge?

**Comment by Muqtxdir** [comment]
We used ubuntu's mono fonts for vte since there wasn't equivalent font package for source code pro fonts

**Comment by kbdharun** [comment]
> Is this ready for merge?

I think yes, but let's wait for matbme's reply. Also, there's my PR for base meta, quick question I should include ikaros right?

**Comment by matbme** [comment]
Yep, it's ready

**Pull request merged**
